print("hi,i am pycharm.what is your name ? ")
name = input()
print("hello, "+name+"\nhow old are you ?"+name)
age = input()
print("ok,good but why you tell me your age? are you crazy!!!")
reason = input()
print("who care's")
print("you said "+reason)
yes = input()
print(name+" let me tell you secret ")
ok = input()
print("i think you are loyal i really hate you ok")
nu = input()
print("hahaha i really made fun of you and you belive me.")
print("ok,this all was prepared by nuha")

