name = input("what is your name?: ")
age = int(input("how old are you? "))
height = float(input("what is your height? "))
print("hello "+name)
print("you are "+str(age)+" years old")
print("you are "+str(height)+"cm tall.")
