print("what is your name")
name = input()
print("welcome ,"+name)
print("how old are you ?"+name)
age = input()
print("what grade are you ?"+name)
grade = input()
print("ok,your name is "+name+" and you are "+age+" years old."+"you are grade "+grade+" student.")